package network

const RESPONSE_OK string = "HTTP/1.1 200 OK\r\n"
const RESPONSE_CREATED string = "HTTP/1.1 201 Created\r\n"
const RESPONSE_NO_CONTENT string = "HTTP/1.1 204 No Content\r\n"
const RESPONSE_MOVED_PERMANENTLY string = "HTTP/1.1 301 Moved Permanently\r\n"
const RESPONSE_FOUND string = "HTTP/1.1 302 Found\r\n"
const RESPONSE_BAD_REQUEST string = "HTTP/1.1 400 Bad Request\r\n"
const RESPONSE_UNAUTHORIZED string = "HTTP/1.1 401 Unauthorized\r\n"
const RESPONSE_FORBIDDEN string = "HTTP/1.1 403 Forbidden\r\n"
const RESPONSE_NOT_FOUND string = "HTTP/1.1 404 Not Found\r\n"
const RESPONSE_METHOD_NOT_ALLOWED string = "HTTP/1.1 405 Method Not Allowed\r\n"
const RESPONSE_INTERNAL_SERVER_ERROR string = "HTTP/1.1 500 Internal Server Error\r\n"
const RESPONSE_BAD_GATEWAY string = "HTTP/1.1 502 Bad Gateway\r\n"
const RESPONSE_SERVICE_UNAVAILABLE string = "HTTP/1.1 503 Service Unavailable\r\n"
const CRLF = "\r\n"
